version: 2

project_name: recco

before:
  hooks:
    - go mod tidy

builds:
  - id: recco
    main: .
    binary: recco
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

    hooks:
      post:
        - cmd: sh -c 'if [ "{{ .Os }}" = "darwin" ]; then codesign --force --deep --options runtime -s - "{{ .Path }}"; fi'

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - repository:
      owner: vitalii-komenda
      name: homebrew-recco
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/vitalii-komenda/Recco"
    description: "A terminal app that recommends Steam games using Gemini AI"
    license: "MIT"
